### ISSUE TITLE
namespace alias breaks Jamroot

### ISSUE THREAD

**Issue by mgaunard** [boostorg/bcp#4]
Using bcp with namespace alias breaks the Jamroot in at least two locations:
 - import tools/boost_install/boost-install wrongly renamed
 - boost-lib rule changes cause DYN_LINK define  to be named wrong, breaking dynamic library exports

**Comment by pdimov** [comment]
This should be fixed by https://github.com/boostorg/boost/commit/d0586e88122f41cd5ac9666db70c37d6f0fc7480.

**Comment by firewave** [comment]
See also https://github.com/boostorg/boost/issues/282

**Comment by jzmaddock** [comment]
This appears to now be fixed in develop (at least Peter's CI tests with namespace aliasing are all passing now), so closing down.
